## arg 1:  the new package version
post_install() {
  xdg-icon-resource forceupdate
  update-mime-database /usr/share/mime
  update-desktop-database -q
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  xdg-icon-resource forceupdate
  update-mime-database /usr/share/mime
  update-desktop-database -q
}

## arg 1:  the old package version
post_remove() {
  xdg-icon-resource forceupdate
  update-mime-database /usr/share/mime
  update-desktop-database -q
}
