post_install() {
	echo -n "Updating desktop mime database, applications database and menu launchers, please wait..."
	glib-compile-schemas /usr/share/glib-2.0/schemas
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	update-desktop-database -q
	update-mime-database usr/share/mime &> /dev/null
	kbuildsycoca4 2> /dev/null
	echo -n "Done."
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
